defmodule ChatterheadWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :chatterhead

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_chatterhead_key",
    signing_salt: "zwTXOaTj",
    same_site: "Lax"
  ]

  # Both timings here are backstops, for a client that vanishes without a word:
  # a crash, a killed tab, a dropped network. A client that leaves on purpose is
  # dropped at once by the `pagehide` beacon in app.js, and one that clicks Leave
  # by the disconnect broadcast in UserAuth.log_out_user/1.
  #
  # websocket timeout: 25s (default 60s). The client heartbeats every 10s
  # (app.js), so a live connection stays well inside the window.
  #
  # longpoll window_ms: 8s (default 10s). Long-poll has no connection for the OS
  # to close, so silence is the *only* signal it has; Phoenix reaps an idle
  # session after `window_ms * 1.5`, on a timer of that same period, so the
  # default trails a departed user for 15–30s. At 8s that is 12–24s, in line with
  # the WebSocket rather than well past it.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], timeout: 25_000],
    longpoll: [connect_info: [session: @session_options], window_ms: 8_000]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :chatterhead,
    gzip: not code_reloading?,
    only: ChatterheadWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :chatterhead
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ChatterheadWeb.Router
end
